[package]
name = "SpeedScore"
version = "0.2.0"
edition = "2021"

[dependencies]
rayon = "1.5"
clap = { version = "4.0", features = ["derive"] }
memmap2 = "0.5"
flate2 = "1.0"
regex = "1.5.4"
indicatif = "0.17.3"
thousands = "0.2.0"
noodles = { version = "0.32", features = ["vcf", "bgzf"] }
